const { Client } = require('pg');
require('dotenv').config();

const connectionString = process.env.DATABASE_URL;

async function fixTableStructure() {
  const client = new Client({
    connectionString: connectionString,
    ssl: { rejectUnauthorized: false }
  });

  try {
    await client.connect();
    console.log('Connected to database to fix table structure...');

    // 1. Remove the fixed default '1'
    await client.query("ALTER TABLE \"Settings\" ALTER COLUMN id DROP DEFAULT;");
    
    // 2. Make it an IDENTITY column (auto-increment)
    // We use 'GENERATED BY DEFAULT AS IDENTITY'
    // But first we need to make sure the sequence starts after the current max ID
    const maxRes = await client.query("SELECT MAX(id) FROM \"Settings\";");
    const nextId = (maxRes.rows[0].max || 0) + 1;
    
    console.log(`Setting next ID to start from: ${nextId}`);
    
    await client.query(`ALTER TABLE "Settings" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH ${nextId});`);

    console.log('✅ Table structure fixed. IDs are now truly automatic.');

  } catch (err) {
    console.error('❌ Error fixing structure:', err.message);
  } finally {
    await client.end();
  }
}

fixTableStructure();
